### ISSUE TITLE
Delay in publishing new content

### ISSUE THREAD

**Issue by payeisa** [StatCan/StatcanPublicationUAT#281]
Two StatsCAN Plus articles were published at 2:00p.m. ad at 2:22p.m. they are still not showing up on the Publications screen of the app.
https://www.statcan.gc.ca/o1/en/plus

Is this related to the api issue Dave fixed?

@Pharste FYI

**Comment by Rajat-Sen** [comment]
Yes, it is related to that as we are facing caching issue on the Prod side.

**Comment by goodyke** [comment]
Hi @Rajat-Sen.  I just verified that the articles that were published to the Plus website at 2pm today are being returned by the api.  Here is the call that I made to verify: https://www.statcan.gc.ca/o1/api/plus/article which gives all required articles when used with the language parameters too: https://www.statcan.gc.ca/o1/en/api/plus/article and https://www.statcan.gc.ca/o1/fr/api/plus/article
Could you please ask Jiandong which parameters that he is adding to his calls to get content for the Publication screen? I could verify those too.  If the newest articles are being returned then could this be caused by not refreshing from the source enough? Or perhaps a problem with the api once it is combined with a parameter?

**Comment by goodyke** [comment]
The fix for #205 was deployed in Production by Drupal at 9:21 this morning and it appears that everything is working... I could also talk to Jiandong about this myself.  @Rajat-Sen which would you prefer?

**Comment by Jiandong-Guo** [comment]
The app is calling:
https://www.statcan.gc.ca/o1/en/api/plus/article?published_after=%272021-11-09%27&page=0
it doesn't return new release published 2:00PM.

**Comment by goodyke** [comment]
Hi Jiandong... I called with those parameters and I am getting the new articles still....
https://www.statcan.gc.ca/o1/en/api/plus/article?published_after="2021-11-09"&page=0

**Comment by ForumG-SC** [comment]
![image](https://user-images.githubusercontent.com/84411852/151244736-3c88bcff-f1a8-4097-84c0-9de310290697.png)

Currently, the app is using this parameter   "article?published_after='2021-11-09'&page=" , if you notice in the date it is single quotes and if you see screenshot above it doesn't return the 2 latest articles.

However, when I change the single quotes to double quotes in date parameter and call api, it is returning the 2 latest articles:
article?published_after="2021-11-09"&page=0
![image](https://user-images.githubusercontent.com/84411852/151244935-1df3a7d1-d1b9-4fd4-b7a6-9615965df688.png)

@goodyke @Jiandong-Guo

**Comment by Jiandong-Guo** [comment]
double quote was used

**Comment by ForumG-SC** [comment]
> double quote was used

No, I just checked the code it is single quotes:
![image](https://user-images.githubusercontent.com/84411852/151245337-db07444e-a0a3-4634-9661-6c5de7401187.png)

**Comment by ForumG-SC** [comment]
When I change the parameters to   `article?published_after="2021-11-09"&page=` , it is returning the latest 2 articles in the app.

**Comment by Jiandong-Guo** [comment]
get latest

**Comment by Jiandong-Guo** [comment]
fixed, please test in next release

**Comment by ForumG-SC** [comment]
Jiandong, change the single quotes to back tabs and it will fix the issue, I just pulled the latest code and I can see that you have used single quotes:
![image](https://user-images.githubusercontent.com/84411852/151245706-7ef68268-b406-4384-bfaf-0f0c93704321.png)

I am replacing the single quote to the back tabs and it will fix the issue,... please pull the latest changes 
![image](https://user-images.githubusercontent.com/84411852/151245879-4ed0fb2f-d4a4-4d19-80a7-0b975fde431f.png)

**Comment by ForumG-SC** [comment]
@goodyke 
![image](https://user-images.githubusercontent.com/84411852/151246107-253f020a-ab13-4411-a788-88f42d0c7598.png)
****

**Comment by zhuelle** [comment]
@lamokar10 this is a backend issue. Please investigate. Thanks!

**Comment by payeisa** [comment]
@weglmar Is this something the app team has been noticing recently? Is there still an issue with publishing delays?

**Comment by weglmar** [comment]
@payeisa It's happening once in a while, I would say at least once or twice a week. We can keep a log of booked time vs published time for the next two weeks and record what device we are noticing it on and which articles (in case there is any sort of correlation). Would that help investigate further?

**Comment by payeisa** [comment]
@zhuelle Priority added.
@weglmar I think that's a good idea!

**Comment by weglmar** [comment]
Hi @zhuelle , I am attaching the results of the test we did. You will see that there are a few articles that were delayed. We're not really sure why. Sometimes it seemed like it was the last one or two articles that we published that morning. 

[StatsCAN app test May 31 to June 10.xlsx](https://github.com/StatCan/StatcanPublicationUAT/files/8941226/StatsCAN.app.test.May.31.to.June.10.xlsx)

**Comment by lamokar10** [comment]
There is already a JIRA ticket with ORPS from March : https://jirab.statcan.ca/browse/ORPS-34

**Comment by weglmar** [comment]
Hi, 
As per Kerry's solution in the Jira ticket, the following was recommended: 

There are two possibilities for the discrepancies that you see in the App that the mobile team could investigate:
1. There is a problem with the call to the backend web service (such as using incorrect syntax, parameters....) - the mobile app team should verify the syntax and parameters.
2. The StatsCAN mobile app logic is not re-calling the ORPS web service to retrieve the mobile app team for every situation or often enough - the mobile app team should verify the logic used.

Is it possible to investigate the above? We are still noticing these delays daily. 

Thank you, 
Martyna

**Comment by payeisa** [comment]
@zhuelle Can we please make this a top priority, amongst the major priorities? Based on the thread, the issue seems to be tied to the type of quotes used in the syntax (single vs double). Is that in fact the case? If so, should t-shirt size really be medium? Thanks, Isabelle

**Comment by Jiandong-Guo** [comment]
@payeisa, the investigate result from front end:
1)Currently, the API call is using https://www.statcan.gc.ca/o1/en/api/plus/article?published_after="2021-11-09"&page=0
2) Every time the publication tab gets focus, the same API will be called again.
Also please provide more information on:
3) Does it happen for every day(I mean the every new publishing) ? if not, that means it's not the problem of calling API, because the calling method is same every day.
4)How to know the newly published article doesn't show up on the app ?, so I can check it from my side.
5) I compared the content from https://www.statcan.gc.ca/o1/en/plus with the our app,  some difference do exists there. the app shows much more articles than the website today(July 11) for example.

**Comment by zhuelle** [comment]
@weglmar and @payeisa Jiandong has completed analysis on the app front side. Please see the comment above from him. There are several items requiring the business feedback (#3, #4, #5, #8). I will assign the ticket back to Martyna for now. Thanks!

**Comment by zhuelle** [comment]
Based on our testing #448 , the issue is on the mobile app side and Jiandong will look into it.

**Comment by weglmar** [comment]
Closing duplicate ticket
